[package]
name = "ctron"
version = "0.2.1"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "MIT"
description = "About ctron"
homepage = "https://dentrassi.de"
repository = "https://github.com/ctron/ctron-rs"

[dependencies]
colored = "2"